### ISSUE TITLE
Training CAN with a Resnet12 backbone on miniImageNet

### ISSUE THREAD

**Issue by AlephNullVEVO** [RL-VIG/LibFewShot#30]
I was trying to reproduce some results from the paper, and had no problem training CAN with a Conv64 backbone using the can.yaml file. However, when using Resnet12 as the backbone I had to lower `episode_size` to 2 (otherwise I'd get a CUDA out of memory error), and after that I couldn't figure out a working configuration to get the training started. Can someone help me out?

config file:
```yaml
includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/CAN.yaml
  - backbones/Conv64F.yaml

episode_size: 2

classifier:
  name: CAN
  kwargs:
    scale_cls: 7 # default
    num_class: 64
    nFeat: 64
    HW: 10

# backbone:
#   name: Conv64F
#   kwargs:
#     is_flatten: False
#     is_feature: False
#     leaky_relu: True
#     negative_slope: 0.2
#     last_pool: False

backbone:
  name: resnet12
  kwargs:
    maxpool_last2: False
    is_flatten: False

# need to modify: core/model/backbone/resnet_18.py:114 stride=1
# backbone:
#   name: resnet18
#   kwargs:
#     is_flatten: False
#     avg_pool: False

#backbone:
#  name: WRN
#  kwargs:
#    depth: 28
#    widen_factor: 10
#    avg_pool: False
#    is_flatten: False
```
log:
```
[11/18/21 12:49:40] INFO     {'data_root':                         trainer.py:50
                             '/storage/miniImageNet--ravi',
                             'image_size': 84, 'use_memory':
                             False, 'augment': True,
                             'augment_times': 1,
                             'augment_times_query': 1,
                             'device_ids': 0, 'n_gpu': 1, 'seed':
                             0, 'deterministic': True, 'log_name':
                             None, 'log_level': 'info',
                             'log_interval': 100,
                             'log_paramerter': False,
                             'result_root': './results',
                             'save_interval': 10, 'save_part':
                             ['emb_func'], 'tag': None, 'epoch':
                             50, 'test_epoch': 5, 'parallel_part':
                             ['emb_func'], 'pretrain_path': None,
                             'resume': False, 'way_num': 5,
                             'shot_num': 1, 'query_num': 15,
                             'test_way': 5, 'test_shot': 1,
                             'test_query': 15, 'episode_size': 2,
                             'train_episode': 100, 'test_episode':
                             100, 'batch_size': 128, 'optimizer':
                             {'name': 'Adam', 'kwargs': {'lr':
                             0.001}, 'other': {'emb_func':
                             0.001}}, 'lr_scheduler': {'name':
                             'StepLR', 'kwargs': {'gamma': 0.5,
                             'step_size': 10}}, 'includes':
                             ['headers/data.yaml',
                             'headers/device.yaml',
                             'headers/misc.yaml',
                             'headers/model.yaml',
                             'headers/optimizer.yaml',
                             'classifiers/CAN.yaml',
                             'backbones/Conv64F.yaml'],
                             'classifier': {'name': 'CAN',
                             'kwargs': {'scale_cls': 7,
                             'num_class': 64, 'nFeat': 64, 'HW':
                             10}}, 'backbone': {'name':
                             'resnet12', 'kwargs':
                             {'maxpool_last2': False,
                             'is_flatten': False}}, 'tb_scale':
                             1.0}
                    INFO     CAN(                                 trainer.py:355
                               (emb_func): ResNet(
                                 (layer1): Sequential(
                                   (0): BasicBlock(
                                     (conv1): Conv2d(3, 64,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn1): BatchNorm2d(64,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (relu):
                             LeakyReLU(negative_slope=0.1)
                                     (conv2): Conv2d(64, 64,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn2): BatchNorm2d(64,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (conv3): Conv2d(64, 64,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn3): BatchNorm2d(64,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (maxpool):
                             MaxPool2d(kernel_size=2, stride=2,
                             padding=0, dilation=1,
                             ceil_mode=False)
                                     (downsample): Sequential(
                                       (0): Conv2d(3, 64,
                             kernel_size=(1, 1), stride=(1, 1),
                             bias=False)
                                       (1): BatchNorm2d(64,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     )
                                     (DropBlock): DropBlock()
                                   )
                                 )
                                 (layer2): Sequential(
                                   (0): BasicBlock(
                                     (conv1): Conv2d(64, 160,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn1): BatchNorm2d(160,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (relu):
                             LeakyReLU(negative_slope=0.1)
                                     (conv2): Conv2d(160, 160,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn2): BatchNorm2d(160,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (conv3): Conv2d(160, 160,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn3): BatchNorm2d(160,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (maxpool):
                             MaxPool2d(kernel_size=2, stride=2,
                             padding=0, dilation=1,
                             ceil_mode=False)
                                     (downsample): Sequential(
                                       (0): Conv2d(64, 160,
                             kernel_size=(1, 1), stride=(1, 1),
                             bias=False)
                                       (1): BatchNorm2d(160,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     )
                                     (DropBlock): DropBlock()
                                   )
                                 )
                                 (layer3): Sequential(
                                   (0): BasicBlock(
                                     (conv1): Conv2d(160, 320,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn1): BatchNorm2d(320,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (relu):
                             LeakyReLU(negative_slope=0.1)
                                     (conv2): Conv2d(320, 320,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn2): BatchNorm2d(320,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (conv3): Conv2d(320, 320,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn3): BatchNorm2d(320,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (maxpool):
                             MaxPool2d(kernel_size=2, stride=2,
                             padding=0, dilation=1,
                             ceil_mode=False)
                                     (downsample): Sequential(
                                       (0): Conv2d(160, 320,
                             kernel_size=(1, 1), stride=(1, 1),
                             bias=False)
                                       (1): BatchNorm2d(320,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     )
                                     (DropBlock): DropBlock()
                                   )
                                 )
                                 (layer4): Sequential(
                                   (0): BasicBlock(
                                     (conv1): Conv2d(320, 640,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn1): BatchNorm2d(640,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (relu):
                             LeakyReLU(negative_slope=0.1)
                                     (conv2): Conv2d(640, 640,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn2): BatchNorm2d(640,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (conv3): Conv2d(640, 640,
                             kernel_size=(3, 3), stride=(1, 1),
                             padding=(1, 1), bias=False)
                                     (bn3): BatchNorm2d(640,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     (maxpool):
                             MaxPool2d(kernel_size=2, stride=2,
                             padding=0, dilation=1,
                             ceil_mode=False)
                                     (downsample): Sequential(
                                       (0): Conv2d(320, 640,
                             kernel_size=(1, 1), stride=(1, 1),
                             bias=False)
                                       (1): BatchNorm2d(640,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                     )
                                     (DropBlock): DropBlock()
                                   )
                                 )
                                 (avgpool):
                             AvgPool2d(kernel_size=5, stride=1,
                             padding=0)
                                 (dropout): Dropout(p=0.0,
                             inplace=False)
                               )
                               (cam_layer): CAMLayer(
                                 (cam): CAM(
                                   (conv1): ConvBlock(
                                     (conv): Conv2d(100, 10,
                             kernel_size=(1, 1), stride=(1, 1))
                                     (bn): BatchNorm2d(10,
                             eps=1e-05, momentum=0.1,
                             affine=True,
                             track_running_stats=True)
                                   )
                                   (conv2): Conv2d(10, 100,
                             kernel_size=(1, 1), stride=(1, 1))
                                 )
                                 (classifier): Conv2d(64, 64,
                             kernel_size=(1, 1), stride=(1, 1))
                               )
                               (loss_func): CrossEntropyLoss(
                                 (logsoftmax): LogSoftmax(dim=1)
                               )
                             )
                    INFO     Trainable params in the model:       trainer.py:357
                             12430610
[11/18/21 12:49:45] INFO     load 38400 image with 64 label.       dataset.py:94
                    INFO     load 9600 image with 16 label.        dataset.py:94
                    INFO     load 12000 image with 20 label.       dataset.py:94
                    INFO     Adam (                               trainer.py:447
                             Parameter Group 0
                                 amsgrad: False
                                 betas: (0.9, 0.999)
                                 eps: 1e-08
                                 initial_lr: 0.001
                                 lr: 0.001
                                 weight_decay: 0

                             Parameter Group 1
                                 amsgrad: False
                                 betas: (0.9, 0.999)
                                 eps: 1e-08
                                 initial_lr: 0.001
                                 lr: 0.001
                                 weight_decay: 0
                             )
                    INFO     ============ Train on the train set   trainer.py:67
                             ============
Traceback (most recent call last):
  File "/src/run_trainer.py", line 12, in <module>
    trainer.train_loop()
  File "/src/core/trainer.py", line 68, in train_loop
    train_acc = self._train(epoch_idx)
  File "/src/core/trainer.py", line 143, in _train
    output, acc, loss = self.model.set_forward_loss(batch)
  File "/src/core/model/metric/can.py", line 413, in set_forward_loss
    support_feat, query_feat, support_targets_one_hot, query_targets_one_hot
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/src/core/model/metric/can.py", line 214, in forward
    prototypes, query_feat
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/src/core/model/metric/can.py", line 149, in forward
    a1 = self.get_attention(a1)  # [1, 5, 75, 36]
  File "/src/core/model/metric/can.py", line 119, in get_attention
    a = F.relu(self.conv1(a))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/src/core/model/metric/can.py", line 92, in forward
    return self.bn(self.conv(x))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [10, 100, 1, 1], expected input[2, 289, 75, 5] to have 100 channels, but got 289 channels instead
```

**Comment by wZuck** [comment]
You can try the following setting for ResNet12
```
classifier:
  name: CAN
  kwargs:
    scale_cls: 7 
    num_class: 64
    nFeat: 640  # notice nFeat should be equal to the channel of Backbone output (64 for Conv64F, 640 for ResNet12 and 512 for ResNet18)
    HW: 5 # notice HW should be equal to the height/weight of Backbone output

backbone:
  name: resnet12
  kwargs:
    avg_pool: False
    is_flatten: False
    maxpool_last2: True
```

**Comment by wZuck** [comment]
Thanks for your advice. We will add some tips in the doc of classifiers and the `README` of each method.
