### ISSUE TITLE
I config as this yaml file './reproduce/RENet/RENet-miniImageNet--ravi-Conv64F-5-5-Table2.yaml'. It runs with errors as below.

### ISSUE THREAD

**Issue by neymar-jr** [RL-VIG/LibFewShot#66]
2023-01-05 06:32:28,367 [INFO] core.trainer: ============ Train on the train set ============
2023-01-05 06:32:28,368 [INFO] core.trainer: learning rate: [0.1, 0.1]
Traceback (most recent call last):
  File "/home/liuxuanchen/Develop/meta-learning/LibFewShot/run_trainer.py", line 29, in <module>
    main(0, config)
  File "/home/liuxuanchen/Develop/meta-learning/LibFewShot/run_trainer.py", line 14, in main
    trainer.train_loop(rank)
  File "/home/liuxuanchen/Develop/meta-learning/LibFewShot/core/trainer.py", line 83, in train_loop
    train_acc = self._train(epoch_idx)
  File "/home/liuxuanchen/Develop/meta-learning/LibFewShot/core/trainer.py", line 169, in _train
    output, acc, loss = self.model(
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/liuxuanchen/Develop/meta-learning/LibFewShot/core/model/abstract_model.py", line 30, in forward
    return self.set_forward_loss(x)
  File "/home/liuxuanchen/Develop/meta-learning/LibFewShot/core/model/finetuning/renet.py", line 410, in set_forward_loss
    (
ValueError: not enough values to unpack (expected 4, got 2)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 49, in _pin_memory_loop
    do_one_step()
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 26, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/multiprocessing/connection.py", line 513, in Client
    answer_challenge(c, authkey)
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/multiprocessing/connection.py", line 762, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/liuxuanchen/anaconda3/envs/torch1.13/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by wZuck** [comment]
You can add the following key-value pair in the YAML file:
```yaml
dataloader_num: 2
```

**Comment by neymar-jr** [comment]
Thanks. It works.
