### ISSUE TITLE
RuntimeError: shape '[-1, 3, 16]' is invalid for input of size 30

### ISSUE THREAD

**Issue by seygodin** [RL-VIG/LibFewShot#77]
I hope this message finds you well. First and foremost, I would like to express my gratitude for your excellent library, which I have been utilizing effectively.

However, I recently encountered an error when using the library with a smaller dataset. While the library functions seamlessly with the standard mini-Imagenet dataset (containing more than 10,000 samples), I experienced an issue when I opted for a smaller training set comprising 640 images. I would like to inquire if there is a minimum size requirement for the training set in order to ensure the library functions optimally.

====My config file====
augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    maxpool_last2: true
    negative_slope: 0.2
  name: Conv64F_prior
batch_size: 4
classifier:
  kwargs: null
  name: ProtoNet
data_root: /home/dataset/cmc_3_label
dataloader_num: 1
deterministic: true
device_ids: 0
episode_size: 1
epoch: 100
image_size: 84
includes:
- cmc_label_headers/data.yaml
- cmc_label_headers/device.yaml
- cmc_label_headers/misc.yaml
- cmc_label_headers/model.yaml
- cmc_label_headers/optimizer.yaml
- classifiers/Proto.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 10
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
    weight_decay: 0.0005
  name: Adam
  other: null
parallel_part:
- emb_func
port: 48828
pretrain_path: null
query_num: 15
rank: 0
result_root: ./paper_result/conv3
resume: false
save_interval: 10
save_part:
- emb_func
seed: 0
shot_num: 1
tag: null
tb_scale: 1.6666666666666667
test_episode: 10
test_epoch: 100
test_query: 5
test_shot: 1
test_way: 3
train_episode: 15
use_memory: false
val_per_epoch: 1
warmup: 0

====Error Code====
Traceback (most recent call last):
  File "size_run.py", line 34, in <module>
    main(0, config)
  File "size_run.py", line 24, in main
    trainer.train_loop(rank)
  File "/home/libfew/core/trainer.py", line 84, in train_loop
    train_acc = self._train(epoch_idx)
  File "/home/libfew/core/trainer.py", line 152, in _train
    for batch_idx, batch in enumerate(zip(*self.train_loader)):
  File "/home/libfew/core/data/dataloader.py", line 197, in __iter__
    yield next(self.iterator)
  File "/root/miniconda3/envs/libfew/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/libfew/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/libfew/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/libfew/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/libfew/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/libfew/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/libfew/core/data/collates/collate_functions.py", line 181, in __call__
    return self.method(batch)
  File "/home/libfew/core/data/collates/collate_functions.py", line 159, in method
    global_labels = torch.tensor(labels, dtype=torch.int64).reshape(
RuntimeError: shape '[-1, 3, 16]' is invalid for input of size 30

**Comment by wZuck** [comment]
I'm going to close this issue. Feel free to reopen if you have any other questions or concerns.
