### ISSUE TITLE
报错：/LibFewShot/core/data/samplers.py", line 111, in __iter__     batch = torch.stack(batch).reshape(-1) RuntimeError: stack expects each tensor to be equal size, but got [16] at entry 0 and [7] at entry 2

### ISSUE THREAD

**Issue by lmqhello** [RL-VIG/LibFewShot#84]
使用了自己的数据集，只修改了data_root，这个出现这个报错，分辨率请问是怎么回事。

**Comment by VincenDen** [comment]
麻烦展示一下更详细的配置文件以帮助我们解决您的问题

**Comment by lmqhello** [comment]
使用自己的数据集，分辨率256*256的，但是报错如下：
Traceback (most recent call last):
  File "run_trainer.py", line 25, in <module>
    main(0, config)
  File "run_trainer.py", line 14, in main
    trainer.train_loop(rank)
  File "/home/lmq/DeepLearning/LibFewShot/core/trainer.py", line 87, in train_loop
    val_acc = self._validate(epoch_idx, is_test=False)
  File "/home/lmq/DeepLearning/LibFewShot/core/trainer.py", line 246, in _validate
    for batch_idx, batch in enumerate(zip(*loader)):
  File "/home/lmq/DeepLearning/LibFewShot/core/data/dataloader.py", line 172, in __iter__
    yield next(self.iterator)
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/lmq/DeepLearning/LibFewShot/core/data/collates/collate_functions.py", line 181, in __call__
    return self.method(batch)
  File "/home/lmq/DeepLearning/LibFewShot/core/data/collates/collate_functions.py", line 160, in method
    -1, self.way_num, self.shot_num + self.query_num
RuntimeError: shape '[-1, 5, 11]' is invalid for input of size 45


配置如下
data_root: ./mini-imagenet/
image_size: 84
use_memory: False
augment: True
augment_times: 1
augment_times_query: 1
workers: 4 # number of workers for dataloader in all threads
dataloader_num: 1



epoch: 50
test_epoch: 5

parallel_part:
  - emb_func

pretrain_path: ~
resume: False
# few shot settings
way_num: 5
shot_num: 1
query_num: 10
test_way: ~ # use ~ -> test_* = *_num
test_shot: ~
test_query: ~
episode_size: 1
train_episode: 100
test_episode: 100

# general model setting
batch_size: 16
val_per_epoch: 1

**Comment by lmqhello** [comment]
includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml
  - backbones/Conv64F.yaml

**Comment by lmqhello** [comment]
图片全部修改成84*84的也是报错，只是图片数量没有那么多

**Comment by 2962313771** [comment]
我也遇到了这个问题

**Comment by 2962313771** [comment]
2023-10-28 05:39:45,309 [INFO] core.trainer: Trainable params in the model: 12424320
2023-10-28 05:39:50,787 [INFO] core.trainer: load 2832 train image with 30 label.
/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 3, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "run_trainer.py", line 25, in <module>
    main(0, config)
  File "run_trainer.py", line 13, in main
    trainer = Trainer(rank, config)
  File "/home/LibFewShot-main/core/trainer.py", line 63, in __init__
    ) = self._init_dataloader(config)
  File "/home/LibFewShot-main/core/trainer.py", line 394, in _init_dataloader
    train_loader = get_dataloader(config, "train", self.model_type, distribute)
  File "/home/LibFewShot-main/core/data/dataloader.py", line 76, in get_dataloader
    dataloader = MultiEpochsDataLoader(
  File "/home/LibFewShot-main/core/data/dataloader.py", line 160, in __init__
    self.iterator = super().__iter__()
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/LibFewShot-main/core/data/dataloader.py", line 141, in __iter__
    yield from iter(self.sampler)
  File "/home/LibFewShot-main/core/data/samplers.py", line 111, in __iter__
    batch = torch.stack(batch).reshape(-1)
RuntimeError: stack expects each tensor to be equal size, but got [16] at entry 0 and [12] at entry 3

**Comment by 2962313771** [comment]
其余的东西都没改，就是放了数据集

**Comment by VincenDen** [comment]
麻烦您确认两方面，1：数据集组织格式是否按照使用文档中规定，每个样本的尺寸一致；2：验证集每个类别的样本量均大于shot_num+way_num

**Comment by 2962313771** [comment]
图片尺寸不一样，还可以改吗

**Comment by 2962313771** [comment]
从代码的地方怎么改呢

**Comment by 2962313771** [comment]
谢谢你的回复

**Comment by 2962313771** [comment]
但是我想使用自己数据集来跑这个项目

**Comment by 2962313771** [comment]
通俗的理解，他这个原理是通过比较两张图片的相似度，逐像素比较，然后就要求尺寸必须相等，是吧

**Comment by VincenDen** [comment]
不好意思我说错了，应该不是图片尺寸的问题， 可以检查一下训练集、验证集、测试集、每个类别的样本数量是否足够支持配置 文件下对应的小样本任务
