### ISSUE TITLE
不管怎么搭配，程序都报错啊

### ISSUE THREAD

**Issue by lmqhello** [RL-VIG/LibFewShot#85]
includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/resnet12.yaml
  - classifiers/Proto.yaml

data_root: ./mini-imagenet/
image_size: 84
use_memory: False
augment: True
augment_times: 1
augment_times_query: 1
workers: 4 # number of workers for dataloader in all threads
dataloader_num: 1

epoch: 50
test_epoch: 5

parallel_part:
  - emb_func

pretrain_path: ~
resume: False
# few shot settings
way_num: 5
shot_num: 1
query_num: 5
test_way: ~ # use ~ -> test_* = *_num
test_shot: ~
test_query: ~
episode_size: 1
train_episode: 100
test_episode: 100

# general model setting
batch_size: 16
val_per_epoch: 1

其他地方没改了，图片是84*84*3的。
报错如下：
[10/28/23 06:57:43] INFO     load 957 train image with 6 label.                   trainer.py:372
                    INFO     load 120 val image with 6 label.                     trainer.py:372
                    INFO     load 120 test image with 6 label.                    trainer.py:372
                    INFO     Adam (                                               trainer.py:372
                             Parameter Group 0
                                 amsgrad: False
                                 betas: (0.9, 0.999)
                                 eps: 1e-08
                                 initial_lr: 0.01
                                 lr: 0.01
                                 weight_decay: 0
                             )
                    INFO     ============ Train on the train set ============     trainer.py:372
                    INFO     learning rate: [0.01]                                trainer.py:372
[10/28/23 06:58:00] INFO     Epoch-(0): [100/100]    Time 0.165 (0.165)      Calc trainer.py:372
                             0.070 (0.069)      Data 0.001 (0.001)      Loss
                             2.477 (16.215)     Acc@1 32.000 (25.760)
                    INFO      * Acc@1 25.760                                      trainer.py:372
                    INFO     ============ Validation on the val set ============  trainer.py:372
Traceback (most recent call last):
  File "run_trainer.py", line 25, in <module>
    main(0, config)
  File "run_trainer.py", line 14, in main
    trainer.train_loop(rank)
  File "/home/lmq/DeepLearning/LibFewShot/core/trainer.py", line 87, in train_loop
    val_acc = self._validate(epoch_idx, is_test=False)
  File "/home/lmq/DeepLearning/LibFewShot/core/trainer.py", line 246, in _validate
    for batch_idx, batch in enumerate(zip(*loader)):
  File "/home/lmq/DeepLearning/LibFewShot/core/data/dataloader.py", line 172, in __iter__
    yield next(self.iterator)
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lmq/anaconda3/envs/pt/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/lmq/DeepLearning/LibFewShot/core/data/collates/collate_functions.py", line 181, in __call__
    return self.method(batch)
  File "/home/lmq/DeepLearning/LibFewShot/core/data/collates/collate_functions.py", line 160, in method
    -1, self.way_num, self.shot_num + self.query_num
**RuntimeError: shape '[-1, 5, 6]' is invalid for input of size 29**

**Comment by VincenDen** [comment]
麻烦您确认两方面，1：数据集组织格式是否按照使用文档中规定；2：验证集每个类别的样本量均大于6
