### ISSUE TITLE
使用时报错too many values to unpack

### ISSUE THREAD

**Issue by hustyisu** [RL-VIG/LibFewShot#95]
在使用提供的配置文件进行测试以下模型时：ProtoNet-resnet12 DN4-resnet12 Renet-resnet12，SKDModel-resnet12 均会报错too many values to unpack(expected 2)，完整报错信息如下

具体报错信息如下：
```
Traceback (most recent call last):
  File "run_trainer.py", line 29, in <module>
    main(0, config)
  File "run_trainer.py", line 14, in main
    trainer.train_loop(rank)
  File "/root/LibFewShot/core/trainer.py", line 83, in train_loop
    train_acc = self._train(epoch_idx)
  File "/root/LibFewShot/core/trainer.py", line 169, in _train
    output, acc, loss = self.model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/LibFewShot/core/model/abstract_model.py", line 30, in forward
    return self.set_forward_loss(x)
  File "/root/LibFewShot/core/model/finetuning/skd_model.py", line 153, in set_forward_loss
    image, target = batch
ValueError: too many values to unpack (expected 2)
```
该如何对代码进行修改？求解答

**Comment by scouthe** [comment]
请问你是怎么解决的，我也遇到了
